spring:
  data:
    mongodb:
      uri: mongodb+srv://it23280892_db_user:HLWvCrdZCSftEFb9@paf.eo9iuqw.mongodb.net/pafdb?retryWrites=true&w=majority&appName=PAF

server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG
    com.smartcampus.ops: DEBUG